In [ ]:
import numpy as np

## Arrays creation

1. Create an empty numpy array

In [ ]:
np.array([])

array([], dtype=float64)

2. Create numpy array with one element

In [ ]:
np.array([1])

array([1])

3. Create numpy array with 5 elements

In [ ]:
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

4. Create numpy array with 1000 zeroes (use `np.zeroes()`)

In [ ]:
np.zeros((1000), dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

5. Create numpy array with 1000 ones  (use `np.ones()`)

In [ ]:
np.ones((1000,), dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

6. Create numpy array with 1000 of fives (use `np.full()`)

In [ ]:
np.full(1000, 5)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,

7. Create an empy 2D array. Print its shape (use `shape` attribute )

In [ ]:
two_d = np.array([[]])
np.shape(two_d)

(1, 0)

8. Create 2D array with 5 rows and 8 columns, filled with zeroes. Print its shape 

In [ ]:
two_d_zeros = np.array([[0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0]])
np.shape(two_d_zeros)

(5, 8)

9. Create 3D array with one element. Print its shape and number of dimensions (use `ndim` attribute) 

In [ ]:
three_d = np.array([[[1]]])
print(three_d.ndim)
np.shape(three_d)


3


(1, 1, 1)

10. Create 3D array of shape (2, 3, 4)

In [ ]:
three_d_two = np.array([[[0, 0, 0, 0], [0, 0, 0, 0] , [0, 0, 0, 0]], [[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]])
np.shape(three_d_two)

(2, 3, 4)

## Reshaping arrays

11. Create 1D array with elements 1, 2, 3, 4. Reshape it to 2D array with shape (2, 2). Use `reshape` method.

In [ ]:
one_d = np.array([1, 2, 3, 4])
np.reshape(one_d, (2, 2))

array([[1, 2],
       [3, 4]])

12. Create 1D array with elements 1, 2, 3, 4. Reshape it to 2D array with shape (4, 1). Now it is a column. Print its shape

In [ ]:
one_d_two = np.array([1, 2, 3, 4])
res = np.reshape(one_d_two, (4, 1))
print(res)
print(res.shape)

[[1]
 [2]
 [3]
 [4]]
(4, 1)


13. Create 2D array with elements 1, 2, 3, 4 and shape (2, 2). Convert it to 1D array by using `ravel()` method.  


In [ ]:
two_d_ravel = np.array([[1, 2],[3, 4]])
print(np.shape(two_d_ravel))
raveled = two_d_ravel.ravel()
print(raveled)

(2, 2)
[1 2 3 4]


14. Create 2D array with elements 1, 2, 3, 4 and shape (2, 2). Convert it to 1D array by using `flatten()` method.

Prove that the following statement is right:

"`flatten` method makes a physical copy of initial array, whereas `ravel` just reindexes elements in array" and uses same .


In [ ]:
two_d_flatten = np.array([[1, 2],[3, 4]])
print(np.shape(two_d_flatten))
flattened = two_d_flatten.flatten()
print(flattened)

(2, 2)
[1 2 3 4]


In [ ]:
# Proof:

raveled[0] = 23
flattened[0] = 23

print(raveled)
print(two_d_ravel)
print(flattened)
print(two_d_flatten)

# the value of two_d_ravel changed while the value of two_d_flatten stayed the same

[23  2  3  4]
[[23  2]
 [ 3  4]]
[23  2  3  4]
[[1 2]
 [3 4]]


## Mathematical operations with arrays

15. Create 1D array add number 42 to every element of this array without using `for` loop

In [ ]:
addition = np.array(range(1, 10))
addition + 42

array([43, 44, 45, 46, 47, 48, 49, 50, 51])

16. Create two 1D arrays of the same length. Calculate sum of these two arrays. The output should be 1D array of the same shape

In [ ]:
arr_one = np.array([2, 3, 4, 5])
arr_two = np.array([5, 4, 3, 2])
arr_one + arr_two

array([7, 7, 7, 7])

17. Create two 2D arrays of the shape (3, 2). Calculate sum of these two arrays. The output should be 2D array of the same shape

In [ ]:
td_arr_one = np.array([[2, 3], [4, 5]])
td_arr_two = np.array([[5, 4], [3, 2]])
td_arr_one + td_arr_two

array([[7, 7],
       [7, 7]])

18. Create 2D array of a shape (2, 3). Add elements `[42, 43, 44]` to every row element-wise. Do not use `for loop`. Print the result, it should be an array of a shape (2, 3)

In [ ]:
td_arr_three = np.array([[3, 2, 1], [1, 2, 3]])
td_arr_three + [42, 43, 44]

array([[45, 45, 45],
       [43, 45, 47]])

19. Create 2D array of a shape (2, 3). Add elements `[42, 43]` to every columnt element-wise. Do not use `for loop`. Print the result, it should be an array of a shape (2, 3)

In [ ]:
td_arr_four = np.array([[1, 1, 1], [1, 1, 1]])
(td_arr_four.T + [42, 43]).T


array([[43, 43, 43],
       [44, 44, 44]])

20. Repeat 5 previous exercises but instead of `+` use `- * / // %` accordingly

In [ ]:
subtraction = np.array(range(50, 60))
subtraction - 42

array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17])

In [ ]:
arr_one = np.array([6, 6, 6, 6])
arr_two = np.array([1, 2, 3, 4])
arr_one * arr_two

array([ 6, 12, 18, 24])

In [ ]:
td_arr_one = np.array([[100, 100], [100, 100]])
td_arr_two = np.array([[1, 2], [4, 5]])
td_arr_one / td_arr_two

array([[100.,  50.],
       [ 25.,  20.]])

In [ ]:
td_arr_three = np.array([[234, 222, 453], [122, 335, 238]])
td_arr_three // [42, 43, 44]

array([[ 5,  5, 10],
       [ 2,  7,  5]])

In [ ]:
td_arr_four = np.array([[42, 43, 44], [43, 44, 45]])
(td_arr_four.T % [42, 43]).T

array([[0, 1, 2],
       [0, 1, 2]])

21. Calculate matrix multiplication of two 2D arrays. Use `@` operator. Print the output and shapes of an inital and resulting arrays

In [ ]:
matrix_one = np.array([[3, 4], [2, 1]])
matrix_two = np.array([[1, 5], [3, 7]])
print(matrix_one.shape)
print(matrix_two.shape)
res = matrix_one @ matrix_two
print(res)
print(res.shape)

(2, 2)
(2, 2)


array([[15, 43],
       [ 5, 17]])

23. Calculate multiplication of 2D array and 1D array. Use `@` operator. Print the output and shapes of an inital and resulting arrays

In [ ]:
matrix_three = np.array([[3, 4], [2, 1]])
matrix_four = np.array([2, 1])
print(matrix_three.shape)
print(matrix_four.shape)
res = matrix_three @ matrix_four
print(res)
print(res.shape)

(2, 2)
(2,)
[10  5]
(2,)


24. Transponse 2D array. Use `.T` attribute

In [ ]:
td_arr_trans = np.array([[1, 3, 5], [5, 7, 12]])
td_arr_trans.T

array([[ 1,  5],
       [ 3,  7],
       [ 5, 12]])

## Indexing 

25. Create 1D array with elements `[40, 41, 42, 43]`. Print first element. Print last element.

In [ ]:
arr_one = np.array([40, 41, 42, 43])
arr_one[[0, -1]]

array([40, 43])

26. Create 1D array with elements `[40, 41, 42, 43]`. Use multiple indexing 


In [ ]:
arr_two = np.array([40, 41, 42, 43])
arr_two[[3, 2, 0]]

array([43, 42, 40])

27. Create 1D array with consequent numbers from 42 to 62 (use `np.arange()`). Make a slice that containes all numbers except the first and the last ones

In [ ]:
nums = np.arange(42,63)
print(nums)
nums[1:-1]

[42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62]


array([43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59,
       60, 61])

28. Create 1D array with consequent numbers from 42 to 62 (use `np.arange()`). Make a slice that containes all elements with odd indexes

In [ ]:
nums = np.arange(42,63)
print(nums)
nums[1::2]

[42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62]


array([43, 45, 47, 49, 51, 53, 55, 57, 59, 61])

29. Create 2D array of a shape (4, 5). Print top left, top right, bottom left and bottom right elements.

In [ ]:
td_arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20]])
print(td_arr)
td_arr[[0, 0, -1, -1], [0, -1, 0, -1]]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


array([ 1,  5, 16, 20])

30. Create 2D array of a shape (4, 5). Output second row

In [ ]:
td_arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20]])
print(td_arr)
td_arr[[1]]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


array([[ 6,  7,  8,  9, 10]])

31. Create 2D array of a shape (4, 5). Output second column

In [ ]:
td_arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20]])
print(td_arr)
td_arr[:, 1]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


array([ 2,  7, 12, 17])

32. Create 2D array of a shape (4, 5). Output 2x2 array from top left corner of the initial array

In [ ]:
td_arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20]])
print(td_arr)
td_arr[:, :-1]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


array([[ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [11, 12, 13, 14],
       [16, 17, 18, 19]])

33. Create 2D array of a shape (4, 5). Output an array with even rows

In [ ]:
td_arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20]])
print(td_arr)
td_arr[0::2]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15]])

## Logical indexing

34. Create 1D array with consequent numbers from 42 to 62 (use np.arange()). Make a slice that containes all numbers >= 50

In [ ]:
nums = np.arange(42,63)
mask = nums >= 50
nums[mask]

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62])

35. Create 1D array with consequent numbers from 42 to 62 (use np.arange()). Make a slice that containes all numbers that are divisible by 3

In [ ]:
nums = np.arange(42,63)
mask = nums % 3 == 0
nums[mask]

array([42, 45, 48, 51, 54, 57, 60])

36. Same as above but first reshape an array to have 4 rows. The output should be still a 1D array

In [ ]:
nums = np.arange(42,62).reshape(4, -1)
print(nums)
mask = nums % 3 == 0
nums[mask]

[[42 43 44 45 46]
 [47 48 49 50 51]
 [52 53 54 55 56]
 [57 58 59 60 61]]


array([42, 45, 48, 51, 54, 57, 60])

## sum, max, min

37. Create 2D array of a shape (3, 5) with random numbers (use `np.random.uniform()`). Find max, min element in this array. Also calculate sum of all elements in this array

In [ ]:
rand_nums = np.random.randint(size = (3, 5), low = 0, high = 100)
print(rand_nums)

print(rand_nums.max())
print(rand_nums.min())
print(rand_nums.sum())

[[ 6 59 32 44 97]
 [32 75 32  7 73]
 [64 14 90 11 88]]
97
6
724


38. Calculate max, min, and sum along vertical axis (use `axis` attribute ). The outputs should be 1D arrays with 5 elements each

In [ ]:
print(rand_nums.max(axis = 0))
print(rand_nums.min(axis = 0))
print(rand_nums.sum(axis = 0))

[64 75 90 44 97]
[ 6 14 32  7 73]
[102 148 154  62 258]


39. Calculate max, min, and sum along horisontal axis. The outputs should be 1D arrays with 3 elements each

In [ ]:
print(rand_nums.max(axis = 1))
print(rand_nums.min(axis = 1))
print(rand_nums.sum(axis = 1))

[97 75 90]
[ 6  7 11]
[238 219 267]


## np.where

In [ ]:
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])

40. For the array above, output all zero elements' indexes. Use `np.where()` 

In [ ]:
np.where(x == 0)[0]

array([2, 4, 5, 8])

<img src="https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/c3301126-ef91-4b5e-9cd6-157e343d979f/d2msg5l-0c7ec9b6-f675-4f93-b425-7bfa5749c4ae.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcL2MzMzAxMTI2LWVmOTEtNGI1ZS05Y2Q2LTE1N2UzNDNkOTc5ZlwvZDJtc2c1bC0wYzdlYzliNi1mNjc1LTRmOTMtYjQyNS03YmZhNTc0OWM0YWUucG5nIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.RrUioaJ02r8zrsLz7IAOw5gIc7QX_zB2odbJCzcZV7s">